#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace LyumaShader
{
    /// <summary>
    /// Routes Poiyomi shaders through LyumaShader's original Waifu2d generator.
    /// Package shaders are read from Packages, while generated shaders are
    /// always written under Assets/LyumaShader.
    /// </summary>
    internal static class PoiyomiWaifu2dAdapter
    {
        private const string PoiyomiPackagePrefix = "Packages/com.poiyomi.toon/";
        private const string GeneratedMarker = "AUTOGENERATED by LyumaShader Waifu2DGenerator";
        private const string OriginalSourceMarker = "Original source file:";
        private const string OriginalShaderGuidTag = "OriginalShaderGUID";
        private const string AnimatedTagSuffix = "Animated";
        private static readonly Dictionary<int, Shader> GeneratedShaderCache = new Dictionary<int, Shader>();

        internal static bool IsSupported(Shader shader)
        {
            return IsPoiyomiShader(shader) || IsWaifu2dShader(shader);
        }

        internal static bool IsWaifu2dShader(Shader shader)
        {
            if(shader == null) return false;

            string path = AssetDatabase.GetAssetPath(shader);
            if(string.IsNullOrEmpty(path) || !path.EndsWith(".shader", StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            bool hasGeneratedMarker = false;
            string originalSourcePath = null;
            try
            {
                using(var reader = new StreamReader(path))
                {
                    for(int lineIndex = 0; lineIndex < 16 && !reader.EndOfStream; lineIndex++)
                    {
                        string line = reader.ReadLine();
                        if(line == null) break;
                        if(line.IndexOf(GeneratedMarker, StringComparison.OrdinalIgnoreCase) >= 0)
                        {
                            hasGeneratedMarker = true;
                        }

                        int sourceIndex = line.IndexOf(OriginalSourceMarker, StringComparison.OrdinalIgnoreCase);
                        if(sourceIndex >= 0)
                        {
                            originalSourcePath = line.Substring(sourceIndex + OriginalSourceMarker.Length).Trim();
                        }
                    }
                }
            }
            catch(IOException)
            {
                return false;
            }

            return hasGeneratedMarker &&
                (IsPoiyomiPath(originalSourcePath) || IsPoiyomiName(shader.name));
        }

        internal static Shader GetWaifu2dShader(Shader source)
        {
            if(source == null) return null;
            if(IsWaifu2dShader(source))
            {
                if(source.FindPropertyIndex("_lyuma_outline_2d") >= 0)
                    return source;
                Shader original = GetOriginalShader(source);
                return original != null
                    ? GetWaifu2dShader(original)
                    : source;
            }
            if(!IsPoiyomiShader(source)) return null;

            int sourceId = source.GetInstanceID();
            Shader cachedShader;
            if(GeneratedShaderCache.TryGetValue(sourceId, out cachedShader) && cachedShader != null)
            {
                return cachedShader;
            }

            Shader generatedShader = Waifu2dGenerator.Waifu2d(source, false);
            if(generatedShader != null) GeneratedShaderCache[sourceId] = generatedShader;
            return generatedShader;
        }

        internal static Shader GetOriginalShader(Shader source)
        {
            if(!IsWaifu2dShader(source)) return null;
            string generatedPath = AssetDatabase.GetAssetPath(source);
            string originalSourcePath = ReadOriginalSourcePath(generatedPath);
            return string.IsNullOrEmpty(originalSourcePath)
                ? null
                : AssetDatabase.LoadAssetAtPath<Shader>(originalSourcePath);
        }

        internal static Shader GetUnlockedSourceShader(Material material)
        {
            if(material == null) return null;
            Shader current = material.shader;
            if(IsSupported(current)) return current;

            string originalGuid = material.GetTag(
                OriginalShaderGuidTag,
                false,
                string.Empty
            );
            if(string.IsNullOrEmpty(originalGuid)) return current;

            string originalPath = AssetDatabase.GUIDToAssetPath(originalGuid);
            Shader original = string.IsNullOrEmpty(originalPath)
                ? null
                : AssetDatabase.LoadAssetAtPath<Shader>(originalPath);
            return IsSupported(original) ? original : current;
        }

        internal static void InitializeMaterial(Material material)
        {
            if(material == null) return;
            material.SetFloat("_2d_coef", 0.99f);
            material.SetFloat("_facing_coef", 0.0f);
            material.SetFloat("_lock2daxis_coef", 1.0f);
            material.SetFloat("_zcorrect_coef", 1.0f);
            material.SetFloat("_lyuma_outline_2d", 1.0f);
            material.SetOverrideTag(
                "_2d_coef" + AnimatedTagSuffix,
                "1"
            );
        }

        private static bool IsPoiyomiShader(Shader shader)
        {
            if(shader == null || IsWaifu2dShader(shader)) return false;
            string path = AssetDatabase.GetAssetPath(shader);
            return IsPoiyomiPath(path) || IsPoiyomiName(shader.name);
        }

        private static bool IsPoiyomiPath(string path)
        {
            if(string.IsNullOrEmpty(path)) return false;
            string normalizedPath = path.Replace('\\', '/');
            return normalizedPath.StartsWith(PoiyomiPackagePrefix, StringComparison.OrdinalIgnoreCase) ||
                normalizedPath.IndexOf("/_PoiyomiShaders/", StringComparison.OrdinalIgnoreCase) >= 0;
        }

        private static bool IsPoiyomiName(string shaderName)
        {
            return !string.IsNullOrEmpty(shaderName) &&
                shaderName.IndexOf(".poiyomi/", StringComparison.OrdinalIgnoreCase) >= 0;
        }

        private static string ReadOriginalSourcePath(string generatedPath)
        {
            if(string.IsNullOrEmpty(generatedPath)) return null;
            try
            {
                using(var reader = new StreamReader(generatedPath))
                {
                    for(int lineIndex = 0; lineIndex < 16 && !reader.EndOfStream; lineIndex++)
                    {
                        string line = reader.ReadLine();
                        if(line == null) break;
                        int sourceIndex = line.IndexOf(OriginalSourceMarker, StringComparison.OrdinalIgnoreCase);
                        if(sourceIndex >= 0)
                        {
                            return line.Substring(sourceIndex + OriginalSourceMarker.Length).Trim();
                        }
                    }
                }
            }
            catch(IOException)
            {
                return null;
            }
            return null;
        }
    }
}
#endif
